### PR TITLE
add user profile

### PR DESCRIPTION
**Pull request by caseykim**
add 'Profile' link on the nav bar
user can edit his/her email address and/or password

https://www.pivotaltracker.com/story/show/111829475

ps. test has not been written yet

### CODE REVIEW

**Comment by kangkyu** [comment]
Don't forget `git rebase master` before push your branch

**Comment by thomas-jung** [comment]
Casey I saw your comments on Hipchat about patch not finding the route. The reason for that is the user spec has ` let!(:user) { FactoryGirl.build(:user) }` which means your user has not been created yet. You need to have a user created since build does not save in order to update the profile.

**Comment by kangkyu** [comment]
@caseykim I told you Thomas will find it

**Comment by thomas-jung** [comment]
We don't need byebug history, otherwise :+1:

**Pull request merged**
