### PR TITLE
feature/112400429-jd Add Word Model

### PR DESCRIPTION
**Pull request by jendiamond**
[feature/112400429-jd](https://www.pivotaltracker.com/projects/1516637/stories/112400429)

Add list of words from:
http://taralazar.com/2014/06/09/list-of-200-fun-cool-and-interesting-words/

### CODE REVIEW

**Comment by thomas-jung** [comment]
Hi @jendiamond . You are very close. When the migration is undone, it should also remove the words from the word table.

**Comment by thomas-jung** [comment]
The migration no longer works. I get 
```
undefined local variable or method `words' for #<AddWordsToWords:0x007ff0134a91f0>/Users/thomas/.rvm/gems/ruby-2.3.0@haikus/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:664:in `block in method_missing'

**Comment by thomas-jung** [comment]
@jendiamond this is not working. Same error as before. 
```
undefined local variable or method `word' for #<AddWordsToWords:0x007f9b0bd108c8>/Users/thomas/.rvm/gems/ruby-2.3.0@haikus/gems/activerecord-4.2.5.1/lib/active_record/migration.rb:664:in `block in method_missing'

**Comment by jendiamond** [comment]
weird that worked for me locally
any direction I should look at?

**Pull request closed without merging**
