### PR TITLE
Ticket #115973581

### PR DESCRIPTION
**Pull request by coffeeexistence**
Reformatted Haiku#new form for friends:
Created User method has_friends?
Added logged_in? to application_controller helper methods
Put friends list into partial: _friends_list.html.erb
Added some css formatting for divs with .friends-list

### CODE REVIEW

**Comment by thomas-jung** [comment]
Hey @coffeeexistence, did you get added as a contributor for this repo? For this project, all contributors push their branches instead of forking. See the README for more details on branch names and PR process. You can ask @charliemcelfresh to get invited if you aren't able to push your branch.

**Comment by thomas-jung** [comment]
Also join us on Hipchat for easier communication. I think Richard has invited you.

**Comment by coffeeexistence** [comment]
I was indeed added as a contributor, I don't believe I was invited on Hipchat though. I will got through the README, branch, and add the changes again. Thank you.

**Comment by thomas-jung** [comment]
I sent you an invite to Hipchat

**Comment by thomas-jung** [comment]
Closing this PR

**Pull request closed without merging**
