### PR TITLE
feature/114618081-kc2

### PR DESCRIPTION
**Pull request by kkchu791**
https://www.pivotaltracker.com/projects/1516637/stories/114618081

### Add automatic login entry for invited friend

Following the link on the email, the invited friend should be given a
session, then redirected to the haiku author's create haiku form

### CODE REVIEW

**Comment by thomas-jung** [comment]
Hey @kkchu791 nice job. I tried it out and it is working. I am not sure whether this is the 'right' way to do it so I wanted to ask why you chose password_salt? Could it have been done with the forgot_password_uuid? I think someone else should review it as well before you merge. :+1:

**Comment by kkchu791** [comment]
hey @thomas-jung, i noticed the invited users did not have a forgot_password_uuid so I thought the password_salt would suffice, but I'm not sure either if this is the right way to go.

**Comment by ypan887** [comment]
Good work Kirk. I am looking at the code. It is working.
I just want to suggest that the maybe the "@invited" in lines controller don't need to be an instance variable.

**Comment by kkchu791** [comment]
@ypan887 good catch

**Comment by ypan887** [comment]
By the way, the title of this ticket says to take invited user to new_password page, and the description says to give it a session and redirect it to the haiku create form. So are we not forcing invited user to change their default password before they can create any haiku lines?

**Comment by kkchu791** [comment]
yes, that was the original ticket and then Charlie suggested we just give the invited a session and direct to the haiku create form. good catch, ill change the title of the ticket.

**Comment by ypan887** [comment]
Then I think your code has done what the ticket is asking.

**Pull request merged**
