### PR TITLE
Feature #111826839 Add ability to create a haiku by writing its first line

### PR DESCRIPTION
**Pull request by kangkyu**
Add create and new method, controller test for HaikusController
Add a nested form on haikus/new template

### CODE REVIEW

**Comment by thomas-jung** [comment]
I believe we are using request specs instead of controller specs. Can we add flash message for when haiku doesn't save? Also your Create Haiku button moves if line is blank.

**Comment by kangkyu** [comment]
What do you mean by "button moves if line is blank"? :facepunch:

**Comment by charliemcelfresh** [comment]
@kangkyu this is a  blocker ticket, why don't you merge it, make a separate ticket for the request specs, and we'll address all the UI stuff in subsequent tickets

**Comment by kangkyu** [comment]
I see, merging

**Pull request merged**
