### PR TITLE
Feature/111829327 mk

### PR DESCRIPTION
**Pull request by knuepwebdev**
https://www.pivotaltracker.com/story/show/111829327

### CODE REVIEW

**Comment by knuepwebdev** [comment]
I'm using this branch for this ticket also:
https://www.pivotaltracker.com/story/show/111829335

**Comment by thomas-jung** [comment]
This is looking good. I can see that the first ticket was completed and I think you're still working on the second ticket. If that's the case, I think it's better practice (my opinion) to have a separate branch for each ticket to have a constant stream of small merges and a consistent team workflow to stay organized. It also makes reviewing the PR easier. :smile:

**Comment by knuepwebdev** [comment]
@thomas-jung Ok sorry about that. I'll be sure to keep a separate branch for each ticket from now on

**Comment by kangkyu** [comment]
:+1:

**Pull request merged**
